### ISSUE TITLE
Does not seem to work on OS X?

### ISSUE THREAD

**Issue by rkrug** [MiJyn/inject2download#1]
Hi

I just saw your script and it sounds brilliant.

But it seems it does not work on OS X, because I see no box poping up?

I tried it on youtude and CommedianInCarsGettingCoffee.

But now I tried it with http://playbb.me/embed.php?w=718&h=438&vid=at/nw/flying_witch_-_01.mp4 (from the source code) and there it seems to work. 

Does it not work on the sites I tried, or is it an OS X issue?

**Comment by MiJyn** [comment]
Thank you for the interest in this script!! For those two, this script is not _exactly_ designed to handle them because their proprietary players only take video IDs as input, and then they extract the video URLs manually from that, somewhere buried deep within their code (that could change at any point in time).

In other words, if I were to add support for them, I'd be fighting against DRM, which, noble as it is, has already been done by excellent scripts such as [youtube-dl](https://rg3.github.io/youtube-dl/) (which supports Comedians In Cars Getting Coffee [via crackle], [among many others](https://rg3.github.io/youtube-dl/supportedsites.html))!

This one is designed to handle general players, ones that aren't DRM'd ... generally, those found in smaller websites where you pay for content (events where they record talks and host them online), some (smaller ... as in, not BBC :P) news sites, most anime/movie/tv streaming sites, etc. :)

youtube-dl, because it's written in python (and not as a browser script) sometimes cannot handle these sites, because some of them tend to be quite obfuscated (and basically require a browser or at least a real javascript interpreter to work).

So to answer your question, it doesn't work on those sites, sadly, but if you want to download from them, youtube-dl is a seriously brilliant script, and can most definitely handle them :)

**Comment by rkrug** [comment]
Thanks for the clarifications - make's sense. I know youtube-dl (and use it as well) but wasn't aware it also supports CommediansInCarsGettingCoffee..

Thanks,
Rainer

**Comment by MiJyn** [comment]
You're welcome, glad I was able to help :) And yeah, youtube-dl is pretty awesome! :D
